### ISSUE TITLE
Le form de création d'organisation ne se reset pas.

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-app#25]
**Décrivez le bogue**
Lorsqu'on utilise les forms de création. Lors de la soumission de ceux-ci, le form se remet à 0. Il efface les champs qui sont remplis et se remet à l'état de base si la soumission réussie.
Cependant, le form de création d'organisation ne se remet pas à 0. Il garde les valeurs entrée dans les champs lors d'un succès de soumission.

**Qu'elles sont les étapes à suivre pour reproduire le bogue ?**
- Être connecté
- Aller dans le formulaire de création d'organisation (/contribuer/organisation)
- Remplir duement le formulaire avec des valeurs qui sont valide.
- Soumettre le formulaire
- Constater que le formulaire est resté de marbre et que l'on peut tenter de ressoumettre immédiatement.

**Qu'est-ce qu'on aurait dû observer**
Le formulaire devrait se remettre à l'état original (Champ vide avec les placeholders)

Observé sur 
PC (Desktop)
Windows 10
Chrome

**Comment by mamarmite** [comment]
C'est fixé
