### ISSUE TITLE
La page "À propos" est visuellement pas terrible pour le test utilisateurs

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-app#26]
**Décrivez le bogue**
Dans la page "À propos" le texte qui est en français est plein de faute et le style n'est pas uniforme. Pour ce qui est du latin, il devrait plutot y avoir un texte en français qui explique.

**Qu'elles sont les étapes à suivre pour reproduire le bogue ?**
- Se diriger sur la page à propos (/a-propos) en cliquant dans le menu Hamburger --> a propos
- Constater le désastre --> "Pourqoi" / le texte en latin / le texte en français est on ne peut plus basique et vide d'émotion.

**Qu'est-ce qu'on aurait dû observer**
Une page expliquant en français la réalité de la base de donnée

Observé sur :
PC (Desktop)
Windows 10
Chrome

**Est-ce que vous auriez une hypothèse pour régler le problème / début d'implémentation ?**
Ajuster le texte et les styles html

**Comment by mamarmite** [comment]
Tu l'as fixed ça @SonofaPancak  ?
