### ISSUE TITLE
Allow PlaceHolder on RichTextArea

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-app#8]
Il serait intéressant de pouvoir inséré un placeholder (texte grisé qui permet à l'utilisateur de voir un exemple de ce qu'il doit écrire dans le component) dans le RichTextArea.
Par exemple, dans le CreateTaxonomyForm, on veut pouvoir mentioner un exemple de raison d'ajouter une taxonomy.

Ce qui est attendu : Que le RichTextArea, lorsque fournit "placeholder" en props, affiche le contenu.
L'utilisation dans CreateTaxonomyForm :
```javascript        
<RichTextarea
                    name="addReason"
                    label="Dites nous en quelques mots la raison de l'ajout"
                    placeholder="Il s'agit du titre de mon métier [...]"
                    onInput={inputHandler}
/>
```

**Comment by mamarmite** [comment]
@SonofaPancak  c'est plus un feature request ça. Ajoute le dans le backlog dans Asana stp :)

**Comment by mamarmite** [comment]
Fixed depuis un bout !
