### ISSUE TITLE
Après l'expiration du token, les pages semblent s'afficher comme si on est encore connecté.

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-app#9]
J'ai remarquer que lorsque sa faisait plus d'une journée, et donc que le token est invalidé, il est possible de naviguer sur le site dans les zones réservée aux utilisateurs connectés et d'y faire des requêtes. De plus, le bouton "Se déconnecter" est visible alors qu'on est "techniquement" pas connecté.
Les requêtes sont invalidée dans le backend et on reçoit une pastille rouge de "Token verification error catched." au frontend.

Comportement attendu : Lorsque le token n'est plus valide, on ne devrait pas pouvoir naviguer dans les pages qui nécessite une authentification et on devrait se retrouvé déconnecté de la plateforme.

Note : Marc-André a mentionner qu'il s'agit peut-être de quelque chose en lien avec le localstorage et qu'il faudrait prendre le "nouveau" pas "l'ancien"

**Comment by mamarmite** [comment]
On ne vérifie pas si le token est légit lorsqu'on load une page.
L'Api a l'URL : /verify-token ([détaillés dans la documentation](https://github.com/Avantage-Numerique/bdsol-api/blob/master/doc/Authentification.md#post-verify-token))

Premier jet basic de design :
- Ajouter le call à verify-token, à chacune des url classé "dashboard"
- Ajuster le isLoggedIn en conséquence.

**Comment by mamarmite** [comment]
J'ai commencé le travail pour le vérify-token. Il reste à déterminer la fréquence qu'on le check.
